### ISSUE TITLE
Furkan Kadıoğlu - Mentör ile Tanışma

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#10]
Gençler, Mentör'ümüz (Furkan Kadıoğlu) belli oldu. Yarın uygun saatte izniniz olursa ben e-posta atıp bir randevu isterim, hem tanışma hem de projenin mevcut durumunu anlatma fırsatımız olur, uygun mudur?

**Comment by S-Toprak** [comment]
Tamamdır hocam in progresse alıyorum

**Comment by ErAk042** [comment]
Uygundur bana

**Comment by sertacates** [comment]
e-posta attım, henüz dönüt gelmedi.

**Comment by sertacates** [comment]
Gençler, mutabıksak ikinci kez e-posta atıyorum, 2 gün içinde cevap vermezse de Tuğba Hanım ile Bora beyi bilgilendiririz. O süreçte de biz yine bildiğimiz şekilde model üzerinden karışıklık matrisi oluşturup o değerlere göre ilerleyerek csv dosyamızda doldurulması gereken alanları doldururuz. Olur mu?

**Comment by sertacates** [comment]
![Image](https://user-images.githubusercontent.com/34302399/182022155-3149e0a3-3b36-41a7-976a-c97e5d14b40f.png)

Gönderdim, dönüt bir iki güne gelirse gidişat ile ilgili Furkan Beyin görüşlerini alırız önerilerine göre ilerleriz eğer dönüt gelmezse mevcut ilerleyişimizi bozmadan devam eder Mentör değişimi talep eder yeni Mentörümüz olursa projede hangi aşamadaysak o aşamadan itibaren gerekli değişiklikleri Mentör'ümüzün önerileri doğrultusunda yaparız. Olur mu? @ErAk042 @S-Toprak

**Comment by sertacates** [comment]
Sertaç Ateş sizi planlanmış Zoom toplantısına davet ediyor.

**Konu:** Mentör Tanışma - İlk Toplantı - Süreç Değerlendirme
**Saat:** 3 Ağu 2022 02:00 ÖS İstanbul

**Zoom Toplantısına Katılın**
https://us04web.zoom.us/j/79698613465?pwd=hT9J7s_m62inhylf4fPeSnYz_h-ksI.1

**Toplantı Kimliği:** 796 9861 3465
**Parola:** TDDIMentor

Eğer tarih veya saat değişikliği olursa haber veririm. Görüşmek dileğiyle. @ErAk042 @S-Toprak

**Comment by sertacates** [comment]
**_Toplantıda Alınan Kararlar_**
- Mevcut gidişatta kodlardan çıktılar temizlensin ve yorumlar artırılsın (Markdown bölgeleri ekleyelim)
- Kural bazlı devam edilen kısımların verimliliği ortaya çıkarılsın,
- Gelişim dokümantasyonu geliştirin ( versiyon - elde edilen bulgular )
- Repo etiketi ve private / Furkan hocamızı da ekleyelim
- Tartışma kısmında literatür taramasında yöntemleri görelim.

**Comment by S-Toprak** [comment]
Repo etiketini acikhack2022 olarak ekleyince herkes gidişatımızı görebilir. Bizim repoyu private yaptığımızda tartışma ve katkı alanlarına erişim imkanımız olmuyor, bu nedenle sadece projeye Furkan hocamızı ekledim. Projeyi tekrar public yapıp etiketi kaldırdım. 20 Ağustosta etiketi de ekleriz.

**Comment by ErAk042** [comment]
Gelişim dokümantasyonunu ekledim, ara ara güncelleyeceğim

**Comment by S-Toprak** [comment]
> * Mevcut gidişatta kodlardan çıktılar temizlensin ve yorumlar artırılsın (Markdown bölgeleri ekleyelim)

Hocam ben de kendi dosyalarımın çıktılarını temizleyip metin halinde yorumlar ekleyince kodları güncellerim

**Comment by ErAk042** [comment]
> **_Toplantıda Alınan Kararlar_**
> 
> * Mevcut gidişatta kodlardan çıktılar temizlensin ve yorumlar artırılsın (Markdown bölgeleri ekleyelim)
> * Kural bazlı devam edilen kısımların verimliliği ortaya çıkarılsın,
> * Gelişim dokümantasyonu geliştirin ( versiyon - elde edilen bulgular )
> * Repo etiketi ve private / Furkan hocamızı da ekleyelim
> * Tartışma kısmında literatür taramasında yöntemleri görelim.

Ben kendi dosyalarımın çıktılarını kaldırıp güncelleyeceğim. Yorumları da zamanla arttıracağım

**Comment by sertacates** [comment]
Galiba tüm istenilenleri yerine getirmek için issues açıldı, görev tanımları yapıldı, var olan çalışmalar güncellendi. Konuyu kapatıyorum.

Bir sonraki MENTÖRÜMÜZ İLE OLAĞAN TOPANTIMIZ 10 Ağustos 2022 Saat 14.00'da gerçekleştirilecektir.
