### ISSUE TITLE
KHK Kategorisinin Doldurulması

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#14]
Seyithan Toprak, bulduğumuz son yönteme göre bugün veya yarın kanun diye kategori edilen bir dokumanın data_text alanından rega_no, rega_tarihi, mevzuat_no ve mevzuat_tarihi alanlarını doldurabilir misin? @S-Toprak

**Comment by S-Toprak** [comment]
Hocam "In Progress"e alıyorum. Üzerinde çalışacağım.

**Comment by sertacates** [comment]
Bu kategoride durum nasıl? 4 alanı dolduralım demiştik, doldurdunuz mu? Yöntemi derin öğrenme demiştik, whatsapptan kural bazlıya döndüğünüzü yazmıştınız, gelişim raporuna / dokümanına değişikliği bulguları ile eklediniz mi?

**Comment by sertacates** [comment]
@S-Toprak yoğunluğun var biliyorum. WhatsApp'tan konuşmuştuk. **Resmi Belge Kategori Ayrımı** için Eray'ın yüklediği dosyadaki gibi hem **satır içi yorum** (inline comment/statement)  hem de program parçasının açıklaması için **not defteri metni** eklersen ipynb dosyana projemiz daha nitelikli olur. Bu arada KHK Kategorisindeki son durum nedir?

**Comment by sertacates** [comment]
Seyithan Toprak, kategori, rega_no, mukerrer_no, rega_tarihi, mevzuat_no, mevzuat_tarihi ve madde_sayisi kısımları ile ilgili son durum nedir? Sadece mukerrer_no mu kaldı? @S-Toprak

**Comment by S-Toprak** [comment]
Hocam TDDI kullanarak yaptığımız işlemde bazen hatalar çıkıyor ama çoğunlukla doğru cevap alıyoruz. Kural bazlı işlemleyse 100 doğruluk oranı aldık. Mükerrer no hariç diğer kısımları doldurabiliyoruz, mükerrer no için de çalışmalarımız devam ediyor

**Comment by sertacates** [comment]
TDDİ için ÇIKARIM kısmını unutmayalım, dokümantasyon bitince haber verirseniz sevinirim.

**Comment by S-Toprak** [comment]
Hocam Eray'la beraber çalışmalarımız sonucunda bütün dosyalar içerisinde 22 hata ile 0.99 doğruluk oranına sahip kural bazlı mükerrer no tespit modülü yazdık. Ve bu modülün KHK kategorisindeki doğruluk oranı da 1.0 'dır. Uygun bir zamanda da kodu düzenleyip dokümantasyonunu da yapacağım.

**Comment by S-Toprak** [comment]
Hocam kodu düzenledim ve dökümantasyonu bitti, yakın zamanda da Eray proje gelişim dökümanına ekleyecektir.
