### ISSUE TITLE
Power Point Template Seçimi

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#15]
Gençler, sunum başlıklarını düşünerek nasıl bir template seçeceğimizi bu kısımda tartışalım.

**Comment by ErAk042** [comment]
Hocam, https://slidesgo.com/ adresindeki veya benzer adreslerdeki bir template'i seçeriz. Sunum başlıklarını çıkarsak daha iyi olur diye düşünüyorum, ne dersiniz? @sertacates @S-Toprak

**Comment by sertacates** [comment]
Bu kaynak bence uygun Eray, sunu başlıklarına karar verdikten sonra sunum tasarımına karar verirsiniz @S-Toprak @ErAk042 

Aşağıdaki sunum tasarımlarına da bakabilirsiniz:
https://www.free-powerpoint-templates-design.com/free-powerpoint-templates-design/
https://www.slidescarnival.com/category/free-templates
https://templates.office.com/en-us/templates-for-powerpoint
https://24slides.com/templates/featured
https://www.canva.com/presentations/templates/
https://www.slideegg.com/free-powerpoint-templates
https://pptxtemplates.com/
https://www.smiletemplates.com/free/powerpoint-templates/0.html

**Comment by ErAk042** [comment]
Sunum İçeriği
- Sunum Karşılama Ekranı (Yarışma Adı, Takım İsmi, Proje Konusu, Proje Ekibi Gibi Veriler)
- Takım Tanıtımı
- Projeye Mentor ve Danışman Katkısının Ne Olduğu
- Problem, Mevcut Durum ve İhtiyaç
- Problemin Çözümü
- Yöntem
- Yaptığımız Teknik Çalışmalar
- Proje Süreci / İş Akışı
- Yol Haritası (Nereye Geldik Nereye Gidebiliriz)
- Proje Videosu
- Teşekkür Ederiz
Bence buna benzer bir içerikte sunum yapabiliriz.

**Comment by sertacates** [comment]
Tüm kural bazlı veri doldurma çalışmamızı bitirelim sonrasında dokümantasyonlardan da yararlanarak sunuma döneriz, olur mu?

**Comment by sertacates** [comment]
Gençler, son aldığımız e-postaya göre sunum yapmayacağınız netleşti, bu konuyu kapatıyoruz. Elinize sağlık.
