### ISSUE TITLE
TDDI ile Madde Sayısı Tespiti Modülü

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#16]
Madde Sayısını daha önceki toplantılarda tek tek yapıyorduk ama bir kişiye verelim ve modül olarak yapsın, diğer dosyalarda bu modülü çağıralım. Belki diğer alanları doldurma çalışmamızı da modüllere çeviririz. Elle değil TDDİ ile madde sayısını halledelim.

**Comment by ErAk042** [comment]
Hocam şimdilik %85 oranında kural bazlı bir sistemimiz var. Ayrıca tüm dokümanların Madde 1 diye içeriği olduğunu tespit ettik. Kural bazlıyı daha da geliştireceğiz eğer %95 oranına yaklaşamazsak farklı bir yöntem ararız. Ya derin öğrenme kullanıp cümle benzerliği ya da nltk içindeki benzerlik araçlarından yararlanırız. https://scikit-learn.org/stable/modules/metrics.html burada da benzerlik ile ilgili yeterince kullanım örneği var. Buradan da yararlanabiliriz.

**Comment by sertacates** [comment]
Eray, **Resmi Belge Kategori Ayrımı** için yüklediğin dosyadaki gibi hem **satır içi yorum** (inline comment/statement)  hem de program parçasının açıklaması için **not defteri metni** eklersen daha nitelikli olur.

**Comment by S-Toprak** [comment]
Hocam kural bazlı sistemde iyileştirmeler yaparak doğruluk oranını %96,57'a çıkartmayı başardık. Dosyada gerekli temizlikler ve belgelemeler yapıldı. Kodu sistemdeki eski sürümüyle değiştiriyorum.

**Comment by sertacates** [comment]
Eline sağlık Seyithan Toprak, inceledim, tamamdır. Açıklamalar yerinde olmuş. Bu başarı oranı iyi, %5'in altına düşmüş, gerisine sonra bakarız, ara yüze odaklanalım.

**Comment by S-Toprak** [comment]
Hocam en son düzenlemelerle artık doğruluk oranı %99'a çıktı. Bence bu sonuç kural bazlı sayım yapmamız fikrini kanıtlar niteliktedir.

**Comment by sertacates** [comment]
Kural bazlı gidelim ama iyi bir bilgisayarda derin öğrenme konusunda da problem olmayabilir yani o ayağı da ihmal etmeyelim. Şimdilik veri doldurma kısmını kural bazlı bitirelim vaktimiz kalırsa modellerin sonuçlarını da ekleriz.

**Comment by S-Toprak** [comment]
Hocam şu an o tür bir bilgisayar'a erişimim yok, aldığımız kararlara bakılırsa önemli de değil zaten. O zaman madde sayısının kural bazlı yapılması konusunda hemfikir olmuşuz gibi gözüküyor.

**Comment by sertacates** [comment]
Bir iki günlüğüne google colab pro hesabı alırız gibi düşünmüştüm. Neyse şimdi kural bazlı gidelim ilk iş bitince ve zaman kalırsa modellere geçeriz

**Comment by S-Toprak** [comment]
Madde Saysını kural bazlı bulunması yeterli hocam, model kullanmaya gerek kalmadı.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
