### ISSUE TITLE
Resmi Belge Kategori Ayrımı

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#17]
Resmi Belge kategori seçimini TDDİ ile yine modül olarak yapalım. Çalışmanın ilk hali tamamlandığında taslağı CODE kısmına atalım ve buradan bilgilendirme yapalım. @ErAk042

**Comment by ErAk042** [comment]
Hocam, madde sayısı bulurken resmi belgelerin hepsinde "madde 1" olduğunu bulduk. Kategoriyi bulmak için de "madde 1"'e kadar olan kısmı işlesek tüm data_text'i işlemezsek akıllıca olur diye düşündük.

**Comment by sertacates** [comment]
Resmi Belge Türü tespitinde hangi aşamadayız? @ErAk042

**Comment by ErAk042** [comment]
Kanun için olan kod hazır yüklüyorum şimdi

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/183292947-e937e9e0-1db2-48a8-a295-c9721ace037d.png)

Eray, eline sağlık, bu kod nispeten iyi olmuş, yukarıdaki satırların çıktıları İngilizce olacak, onları Türkçe yapalım. Ayrıca **ÇIKARIMLAR** kısmında da Doğruluk (Accuracy) , Kesinlik (Precision) , Hassasiyet (Sensitivity), Duyarlılık (Recall) ya da F1 Puanı (F1 Score) gibi verileri de işleyelim.

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/183389335-0c4ce040-347a-43db-9c6a-3f566b52130b.png)

Eline sağlık Eray, gelişim raporunu da güncelleyelim.

**Comment by S-Toprak** [comment]
Hocam Belge Ayrım kodunu şu anlık Özelge hariç bütün kategorilere uyarladım, Resmi Gazete kategorisi hariç güzel sonuçlar aldım. Normalde belgeye işlemiştim ama bir sorun çıktı. Yarın Özelge kodunu da ekleyince onu da tabloya ekleyeceğim.

**Comment by S-Toprak** [comment]
Hocam Özelgeyi de ekledim, KHK kodunda küçük bir sorun varmış onu da düzelttim. Bütün verileri de proje gelişim raporuna işledim.

**Comment by sertacates** [comment]
Elinize sağlık gençler.

**Comment by S-Toprak** [comment]
Bütün kategoriler için kategori ayrım kodları hazır hocam, Eray'da onları son koda dahil ediyor.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
