### ISSUE TITLE
Proje Gelişim Raporu - Dokümantasyon

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#18]
Projemizin modüllerinin gelişim aşamalarını takip edebilmemiz için bu aşamaları Yöntem, Verimlilik ve benzer bulgularla kayıt altına alalım. @S-Toprak @ErAk042

**Comment by sertacates** [comment]
Dosyanızı md uzantılı yaptım. Biçimli yazarsanız daha güzel gözükür. İşlediklerini okudum. İyi olmuş. Bulgularla destekleyerek neyi neden yaptığınızı belirtmişsiniz.

**Comment by sertacates** [comment]
Çalışmalarınızda güzel ilerliyorsunuz ama https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md sayfası güncellenmemiş, dokümantasyona da ağırlık verelim, son güne kalmasın.

**Comment by sertacates** [comment]
Çalışmalarınızda güzel ilerliyorsunuz ama https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md sayfası güncellenmemiş, dokümantasyona da ağırlık verelim, son güne kalmasın. @S-Toprak @ErAk042

**Comment by S-Toprak** [comment]
@ErAk042 KHK veri işleme dosyasını güncelledim, hem TDDI modelleri hem de kural tabanlı arama'yla yapılmış örnekler ve performans tabloları var, dosyaya işlersen iyi olur sendeki dosya bende yok.

**Comment by sertacates** [comment]
**2. Data_text İçinden Veri Çıkarım Modülü** bu kısmın üzerinden geçeceğiz, her belgede aynı modeli kullanmayabiliriz. Şimdilik doğru yani soru - cevap için modeller bunlar belki zamanımız kalırsa özet/maskeleme tarzı işlere girersek güncelleme yapabiliriz. Elinize sağlık.

**Comment by sertacates** [comment]
Bu arada Mükerrer no istatistikleri el yakıyor... İyi sonuçlar almışsınız. İşi çözmüşsünüz.
