### ISSUE TITLE
Gereklilikler İle İlgili Kütüphane Sürüm Bilgisi Oluşturulması

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#19]
Gençler, kullandığımız kütüphaneler ve onların bizim kodları çalıştıran sürümleri bilgisi için gereksinimler.txt diye bir dosya oluşturalım.
kutuphaneIsmi == surumBilgisi

**Comment by sertacates** [comment]
Sadece tek girdi var. Oysa kodlamalarınız devam ediyor. Lütfen güncelleme yapın. @ErAk042 @S-Toprak

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/183293495-eb4f51e4-b111-4aad-85ce-fad98c6c5917.png)

Gençler, elinize sağlık 4 kütüphane için bilgileri yazmışsınız. **Resmi Belge Kategori Ayrımı** yüklenen dosyada da galiba farklı kütüphaneler var. Onların da verilerini işlersiniz değil mi? @S-Toprak @ErAk042

**Comment by S-Toprak** [comment]
Hocam şu anki kullandığımız tüm kütüphaneler eklendi. Eğer uygunsa issue'yı geçici olarak kapatıyorum

**Comment by sertacates** [comment]
Tamamdır, gözümüze çarpan oldukça o kısma ekleriz.
