### ISSUE TITLE
Code of Conduct oluşturulması

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#22]
![Image](https://user-images.githubusercontent.com/34302399/183293896-a12fa75b-7c88-42d7-863b-56a53ad5f7d8.png)

Gençler, bu kısmı kontrol ederken fark ettim, CODE_OF_CONDUCT.md isimli bir dosya oluşturmamız gerekiyor. İlgilenirseniz sevinirim. @ErAk042 @S-Toprak

**Comment by S-Toprak** [comment]
Hocam Konuyla ilgilendim, issue'yı kapatıyorum.
