### ISSUE TITLE
CODE_OF_CONDUCT.md Dosyasını düzenleyelim.

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#23]
Seyithan Toprak, CODE_OF_CONDUCT.md dosyasında standart/klasik bilgiler İngilizce olarak duruyor, İnternet üzerinden benzer paylaşımlara bakım TDDİ yarışma sürecini de kapsayacak şekilde (Diğer yarışmacılardan gelen sorulara etik ve dürüst oyun çerçevesinde cevap verilecektir, esinlenme olursa belirtilecektir gibi maddeler) güncellemeler yapalım. @S-Toprak

**Comment by S-Toprak** [comment]
Hocam bu konuya akşam daha detaylı bakacağım, şimdilik metni Türkçe çevirisiyle değiştirdim

**Comment by sertacates** [comment]
Eline sağlık, güncellemeleri yaptıktan sonra bilgi verirsin olur mu?

**Comment by S-Toprak** [comment]
Hocam dosyayı bizim yarışmaya göre biraz düzenledim, önerilerinizi bekliyorum

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/184691796-28ea6d61-3171-4edc-bb5c-62dd703b6e8b.png)
Buradaki görsele el atarsanız iyi olur.

![image](https://user-images.githubusercontent.com/34302399/184691985-6d430c3e-d660-4b48-8312-f9023a88ce45.png)
Sonuncuya intihal kısmını da ekleyebiliriz.

![image](https://user-images.githubusercontent.com/34302399/184692166-e72a8bc3-989f-4109-9116-fe1f59b2a937.png)
Bu kısmı anlayamadım

Eline sağlık Seyithan Toprak çok nitelikli ve yerinde bir doküman olmuş.

**Comment by S-Toprak** [comment]
Tamamdır hocam gözden kaçan kısımları düzenler ve issue'yı kapatırım o zaman

**Comment by sertacates** [comment]
Uygundur, kolay gelsin
