### ISSUE TITLE
Haftalık Toplantı 01

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#24]
Konu: Mentörümüzle Haftalık Toplantımız 01
Saat: 10 Ağu 2022 02:30 ÖS İstanbul

Zoom Bağlantısı
https://us04web.zoom.us/j/74936946047?pwd=d7qQ-e1L430DUcnQeP16BPjqJTefwj.1

Toplantı Kimliği: 749 3694 6047
Parola: MENTOR_TP1

**Comment by sertacates** [comment]
14:45 diye hocamız belirtmişti. 14:45'te görüşmek dileğiyle

**Comment by sertacates** [comment]
**_Ana Gündem:_**
- Proje İlerlemesi
- Veri Biliminde benzerlik ölçümü
- Modellerin (huggingface) hem soru/cevap hem de cümle benzerliği konusundaki yavaşlıkları nasıl giderilebilir?
- Diğer sorular ve Mentör görüşü

**Comment by ErAk042** [comment]
14:45 te görüşürüz

**Comment by S-Toprak** [comment]
1 Saat Sonra görüşürüz hocam

**Comment by sertacates** [comment]
Proje gelişim raporunun güncellenmesi gerekiyor.
Belge türünde yapıldığı gibi tüm alan doldurma çıkarımlarını hesaplanması gerekiyor.
Görev ile ilgili hedefleri kontrol edelim

**Comment by sertacates** [comment]
Gençler, başarı / performans çizelgesi için aşağıdaki taslak kullanılabilir

![image](https://user-images.githubusercontent.com/34302399/183905344-7898fd47-68c9-4b78-b18d-e7721619e5b0.png)

Bugün eldeki verilerle dolduralım @ErAk042

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/183905570-a916551f-f942-490f-866b-9da930ce8317.png)

Bu şekilde de Seyithan Toprak sen ikinci bir tablo oluşturursan sevinirim. @S-Toprak

**Comment by sertacates** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Bordo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Bordo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Belge Kategorisi Bulma   Görevi
-- | --
YÖNTEM | Doğruluk (Accuracy) | Keskinlik (Precision) | Hassasiyet (Sensitivity) /   Duyarlılık (Recall) | Özgüllük (Specificity) | F1-Puanı (F1 Score)
Kural Bazlı Kanun Bulma   Yöntemi |   |   |   |   |  
Model A Kullanılarak Kanun   Bulma Yöntemi |   |   |   |   |  
Model B Kullanılarak Kanun   Bulma Yöntemi |   |   |   |   |  
Model C Kullanılarak Kanun   Bulma Yöntemi |   |   |   |   |  
Model D Kullanılarak Kanun   Bulma Yöntemi |   |   |   |   |  
Model E Kullanılarak Kanun   Bulma Yöntemi |   |   |   |   |  



</body>

</html>

**Comment by sertacates** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

**Comment by sertacates** [comment]
Süreç Yönetimi Tablomuzdan sırayla devam edelim.
