### ISSUE TITLE
CONTRIBUTING.md dosyasını düzenleyelim mi

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#25]
Çalışmanıza katkı sağlayacaklar için bir Katılımcı Yönergeleri github hesabına ekleyelim mi?

Doküman: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

Örnek: https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

@ErAk042 @S-Toprak

**Comment by S-Toprak** [comment]
Tamamdır hocam, üzerinde çalışacağım.

**Comment by sertacates** [comment]
Yarışma kapsamında biz çalışıyoruz yarışmadan sonra sizlerin katkısını bekliyoruz gibi mi yapsak?

**Comment by S-Toprak** [comment]
Linki şimdi inceledim hocam, ona göre bir ürün ortaya koyarız Erayla

**Comment by sertacates** [comment]
Kolay gelsin

**Comment by S-Toprak** [comment]
Hocam Contributing.md dosyasını düzenledim ve sonuçtan mutluyum. Eğer yapmamı istediğiniz değişiklikler olursa lütfen haberdar ediniz.

**Comment by sertacates** [comment]
![image](https://user-images.githubusercontent.com/34302399/184690944-a0a24e86-65c4-42ce-bb4f-27dc1d8adf9f.png)

*yarışamsı* kelimesini düzeltelim.

![image](https://user-images.githubusercontent.com/34302399/184691069-54992803-9801-4cad-9114-9be927847857.png)

projeye diyelim.

![image](https://user-images.githubusercontent.com/34302399/184691293-12dcc69f-9ef1-4a7b-963c-2f55021049b0.png)

Harika olmuş özellikle tartışma sayfası açmanız çok hoşuma gitti. Elinize sağlık.

![image](https://user-images.githubusercontent.com/34302399/184691462-aa8f84f9-b43a-4033-b129-7069772b1715.png)

Vay vay vay, ne ara öğrendiniz bu kısımları, çok iyi teşekkür ederim.

NOT: Son satır sanki dükkan benim gibi olmuş, daha uygun bir şey yazılabilir. Yani CONTRIBUTING.md dosyasını sen hazırladın Seyithan ama ekibin de projede sanki biraz katkısı vardır ;)

**Comment by S-Toprak** [comment]
Tamamdır hocam değişiklikleri dikkate alarak düzeltmeye başlıyorum

**Comment by S-Toprak** [comment]
Tamamdır Hocam, başka değişikliğe gerek yoksa issue'yı kapatıyorum.

**Comment by sertacates** [comment]
Eline sağlık Seyithan Toprak, kapat gitsin. Bu da bitsin.
