### ISSUE TITLE
Resmi Gazete Kategorisinin doldurulması

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#27]
Hocam KHK kategorisinden sonra diğer kategorilerde çalışmaya başlamalıyız. Şimdilik ben bu kategoriyle ilgileneceğim eğer sorun yoksa. @sertacates

**Comment by sertacates** [comment]
Seyithan Toprak, sorun yok, şimdiden eline sağlık.

**Comment by sertacates** [comment]
Tamamdır Seyithan Toprak, TO DO listesinden başka bir tane seçersen ve ilerlersen sevinirim.

**Comment by S-Toprak** [comment]
Hocam Eray'la kodu hazırladık. Gerekli yerlere dökümantasyonunu da yapacağız.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
