### ISSUE TITLE
Komisyon Raporu Kategorisinin doldurulması

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#29]
Bu alanda çalışmaya başlıyorum hocam.

**Comment by sertacates** [comment]
Tamamdır, kolay gelsin Seyithan Toprak

**Comment by S-Toprak** [comment]
Kod hazır hocam. Github'a yükledim ve dökümantasyonunu birazdan yapacağım.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
