### ISSUE TITLE
Sosyal Medya Görünümü - Logo, Etiketler ve Proje Açıklaması

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#3]
Gençler, isterseniz şimdiden https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/converting-a-user-into-an-organization bu dokümanı okuyup sosyal medya için bir logo veya banner tasarlarsanız sevinirim.

**Comment by ErAk042** [comment]
Hocam in progress e alıyorum üzerinde çalışacağız

**Comment by S-Toprak** [comment]
Hocam mevcut logo taslağımız aşağıdaki gibidir
![taMAM Logo Tasarım (1)](https://user-images.githubusercontent.com/109174796/180514420-8fec6047-85c0-43e4-a1ce-841347f147d5.png)
.

**Comment by sertacates** [comment]
Bu müthiş, biriniz kurum sosyal medya kısmına eklesin ve bu başlığı DONE (Yapılmış/Bitmiş) kısmına alıp başlığı (issue'yu) kapatalım.
