### ISSUE TITLE
Yönetmelik Kategorisinin Doldurulması

### ISSUE THREAD

**Issue by ErAk042** [iflGARAJI10100/taMAM#32]

**Comment by ErAk042** [comment]
Hocam bu konuda çalışmalara başladım bir gelişme oldukça bildiririm şu anlık in progress e alıyorum

**Comment by ErAk042** [comment]
Bu konudaki çalışmalarım bitti. Şu anda yönetmelikte %95 üzeri doğrulukla çalışan bir modül var. Bu issue yu kapatıyorum.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
