### ISSUE TITLE
Genelge Kategorisinin doldurulması

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#33]
Hocam bu alanda çalıştığım bir kodum var. Performansını düzelltiğimde Github'a yükleyeceğim

**Comment by S-Toprak** [comment]
Dökümantasyonu tamam hocam, performansda da sorun olmadığı için issue'yı kapatıyorum

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
