### ISSUE TITLE
Tebliğ Kategorisinin doldurulması

### ISSUE THREAD

**Issue by ErAk042** [iflGARAJI10100/taMAM#34]

**Comment by ErAk042** [comment]
Bu kategoride ben çalışacağım hocam gelişme oldukça buradan bildiririm

**Comment by ErAk042** [comment]
Şu anda bu konuda çalışmalarım bitti, %95 üzeri doğrulukla çalışan bir modül hazır. Bu issue yu kapatıyorum.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
