### ISSUE TITLE
Özelge Kategorisinin doldurulması

### ISSUE THREAD

**Issue by ErAk042** [iflGARAJI10100/taMAM#35]

**Comment by ErAk042** [comment]
Hocam ben bu konuda çalışıyorum gelişme oldukça bildireceğim

**Comment by sertacates** [comment]
Tamamdır. Kolay gelsin.

**Comment by ErAk042** [comment]
Diğer issue da belirttiğim gibi bu konuda çalışmalarım bitti. Issue yu kapatıyorum.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
