### ISSUE TITLE
Resmi Gazete Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#38]
# **RESMİ GAZETE KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaResmiGazete.ipynb) ulaşabilirsiniz.
- **'mukerrer_no'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeMukerrerNoTespitModulu.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma **mevcuttur.** Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeResmiGazete.ipynb) ulaşabilirsiniz.
- **'rega_no'** | Bu alandaki 546 değerin doldurulmasıyla ilgili çalışma **mevcuttur.** Belirtilen çalışmanın dökümantasyonu  üzerinde daha fazla durulmalıdır.
- **'rega_tarihi'** | Bu alandaki 546 değerin doldurulmasıyla ilgili çalışma **mevcuttur.** Belirtilen çalışmanın dökümantasyonu üzerinde daha fazla durulmalıdır.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
