### ISSUE TITLE
Komisyon Raporu Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#39]
# **KOMİSYON RAPORU KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaKomisyonRaporu.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma **mevcuttur.** Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeKomisyonRaporu.ipynb) ulaşabilirsiniz.
- **'donem'** | Bu alandaki 500 değerin doldurulmasıyla ilgili çalışma **mevcuttur.** Belirtilen değerler 74 Hatayla ve 0.85 Doğrulukla **Kabul Edilebilir Hatalı** çalışmaktadır.
**NOT**: **'donem'**  alanının doldurulması sadece **"21. Dönem ve sonrasındaki Dönemler"** deki belgelerde beklenir.
- **'sira_no'** | Bu alandaki 500 değerin doldurulmasıyla ilgili çalışma **mevcuttur.** Belirtilen değerler 131 Hatayla ve 0.73 Doğrulukla **Kabul Edilebilir Hatalı** çalışmaktadır.

**Comment by S-Toprak** [comment]
Dökümantasyonu ve Yüklemesi tamam hocam. Performansı sonra zaman kalırsa arttırmaya çalışacağım

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
