### ISSUE TITLE
Genelge Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#40]
# **GENELGE KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaKomisyonRaporu.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma **mevcuttur**. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeGenelge.ipynb) ulaşabilirsiniz.
- **'mevzuat_tarihi'** | Bu alandaki 385 değerin doldurulmasıyla ilgili çalışma **mevcuttur.** 385 değer 0 Hata ve 1.0 Doğruluk Oranıyla **Hatasız** Olarak Bulunmuştur.
- **'mevzuat_no'** | Bu alandaki 342 değerin doldurulmasıyla ilgili çalışma **mevcuttur.** 342 değer 0 Hata ve 1.0 Doğruluk Oranıyla **Hatasız** Olarak Bulunmuştur.
**NOT**: **'mevzuat_no'**  alanının doldurulması sadece **'belge_sayi'** alanının **nan** olduğu belgelerde beklenir.
- **'belge_sayi'** | Bu alandaki 43 değerin doldurulmasıyla ilgili çalışma **mevcuttur .** 43 değer 0 Hata ve 1.0 Doğruluk Oranıyla **Hatasız** Olarak Bulunmuştur.
**NOT**: **'belge_sayi'**  alanının doldurulması sadece **'mevzuat_no'** alanının **nan** olduğu belgelerde beklenir.

**Comment by S-Toprak** [comment]
Hocam bu kategori için kodu yazdım
Dökümantasyonunu da yarına yapacağım.

**Comment by S-Toprak** [comment]
Dökümantasyon tamamdır hocam.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
