### ISSUE TITLE
Cumhurbaşkanlığı Kararnamesi Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#41]
# **CUMHURBAŞKANLIĞI KARARNAMESİ KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaCumhurba%C5%9Fkanl%C4%B1%C4%9F%C4%B1Kararnamesi.ipynb) ulaşabilirsiniz.
- **'mukerrer_no'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeMukerrerNoTespitModulu.ipynb) ulaşabilirsiniz.
- **'madde_sayisi'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiMaddeSayisiBulmaMod%C3%BCl%C3%BC.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeCumhurba%C5%9Fkanl%C4%B1%C4%9F%C4%B1Kararnamesi.ipynb) ulaşabilirsiniz.
- **'rega_no'** | Bu alandaki 54 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
- **'rega_tarihi'** | Bu alandaki 54 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
- **'mevzuat_no'** | Bu alandaki 54 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
- **'mevzuat_tarihi'** | Bu alandaki 47 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
**NOT**: **'mevzuat_tarihi'**  alanının doldurulması sadece **'mevzuat_tarihi'**  değerinin mevcut olduğu belgelerde istenmektedir.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
