### ISSUE TITLE
Tüzük Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#42]
# **TÜZÜK KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaT%C3%BCz%C3%BCk.ipynb) ulaşabilirsiniz.
- **'mukerrer_no'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeMukerrerNoTespitModulu.ipynb) ulaşabilirsiniz.
- **'madde_sayisi'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiMaddeSayisiBulmaMod%C3%BCl%C3%BC.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIsleme_T%C3%BCz%C3%BCk_TDDIsiz_v1.ipynb) ulaşabilirsiniz.
- **'rega_no'** | Bu alandaki 82 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
- **'rega_tarihi'** | Bu alandaki 82 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
- **'mevzuat_no'** | Bu alandaki 82 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.
- **'mevzuat_tarihi'** | Bu alandaki 82 değer **Hatasız** şekilde **1.0** Doğrulukla doldurulmuştur.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
