### ISSUE TITLE
Yönetmelik Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#43]
# **YÖNETMELİK KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaYonetmelik.ipynb) ulaşabilirsiniz.
- **'mukerrer_no'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeMukerrerNoTespitModulu.ipynb) ulaşabilirsiniz.
- **'madde_sayisi'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiMaddeSayisiBulmaMod%C3%BCl%C3%BC.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma **mevcut değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.
- **'rega_no'** | Bu alandaki 597 değerin doldurulmasıyla ilgili çalışma **mevcuttur değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.
- **'rega_tarihi'** | Bu alandaki 597 değerin doldurulmasıyla ilgili çalışma **mevcuttur değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.

**Comment by ErAk042** [comment]
Bu kategorideki çalışmalarım da bitti. Şu anda %90 üzeri doğrulukla çalışan kural bazlı bir modü var. Bu issue yı kapatıyorum.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
