### ISSUE TITLE
Tebliğ Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#44]
# **TEBLİĞ KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulmaTeblig.ipynb) ulaşabilirsiniz.
- **'mukerrer_no'** | Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiVeriIslemeMukerrerNoTespitModulu.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma **mevcut değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.
- **'rega_no'** | Bu alandaki 623 değerin doldurulmasıyla ilgili çalışma **mevcuttur değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.
- **'rega_tarihi'** | Bu alandaki 623 değerin doldurulmasıyla ilgili çalışma **mevcuttur değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.

**Comment by ErAk042** [comment]
Bu kategoride yüksek doğruluk ile çalişan bir modül geliştirdim ve yükledim. İssue'yu kapatıp done a alıyorum, ileride gerekirse yeniden açarız.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
