### ISSUE TITLE
Özelge Kategorisinde Alan Doldurma

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#45]
# **ÖZELGE KATEGORİSİNDE DOLDURULMASI GEREKEN ALANLAR (GÜNCEL)**
Aşağıda listelenen alanların doldurulmasıyla ilgili dokümantasyona [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/ProjeGeli%C5%9FimDok%C3%BCman%C4%B1.md) ulaşabilirsiniz.
- **'kategori'** |  Bu alanın doldurulması ile ilgili çalışma mevcuttur. Çalışmaya [Buradan](https://github.com/iflGARAJI10100/taMAM/blob/main/aramaProjesiKategoriBulma%C3%96zelge.ipynb) ulaşabilirsiniz.

Aşağıdaki alanların doldurulmasıyla ilgili çalışma **mevcut değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.
- **'mevzuat_tarihi** | Bu alandaki 750 değerin doldurulmasıyla ilgili çalışma **mevcuttur değildir.** Belirtilen çalışma üzerinde daha fazla durulmalıdır.

**Comment by ErAk042** [comment]
bu konudaki çalışmamı bittirdim şu anda %80 doğrulukla çalışan kural bazlı bir modülümüz var. Bu issue yı kapatıyorum

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
