### ISSUE TITLE
Kodların Dosyalanması

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#48]
Daha güzel bir interface için aynı türdeki kodları dosyalayıp listeleyebiliriz.

**Comment by S-Toprak** [comment]
Bunun kodları gösteren linklerde sorun çıkarabileceğini fark ettim. Bu fikri es geçelim

**Comment by sertacates** [comment]
Farklı bir yaklaşım, başka bir projede değerlendiririz. 
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.
