### ISSUE TITLE
\#acikhack2022 etiketinin eklenmesi

### ISSUE THREAD

**Issue by S-Toprak** [iflGARAJI10100/taMAM#49]
En sonda 23.30 gibi etiketi ekleriz.

**Comment by S-Toprak** [comment]
Hocam etiket doğru oldu mu? Çünkü #acıkhack2022tddi diye bir tane de varmış

**Comment by S-Toprak** [comment]
Tamamdır hocam, etiketi düzelltim.

**Comment by sertacates** [comment]
Elinize sağlık Seyithan Toprak, artık yarışma gününü bekleyeceğiz.

**Comment by Seyfideniz123** [comment]
![20220824_115957.png](https://user-images.githubusercontent.com/109550657/186376926-577913de-4599-4492-91fd-45914520e964.png)

**Comment by sertacates** [comment]
> ![20220824_115957.png](https://user-images.githubusercontent.com/109550657/186376926-577913de-4599-4492-91fd-45914520e964.png)

Sanki bizim kurallara göre burada böyle bir paylaşım yapılmaması gerekiyordu. @ErAk042 @S-Toprak @Seyfideniz123
