### ISSUE TITLE
Ara Yüz tasarımını yapalım.

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#5]
Gençler, ara yüz için ne düşünüyorsunuz? https://docs.python.org/3/library/tkinter.html Tk Interface yani Tk ara yüz kütüphanesi ile bir şeyler yapalım mı?

**Comment by S-Toprak** [comment]
Konuyu "In Progress" a alıyorum hocam. Üzerinde çalışacağım.

**Comment by sertacates** [comment]
Seyithan Toprak veya Eray, biriniz ara yüz dosyasındaki kodlara yorum yazsın. Yorum yazmadan doğrudan kodları atmışsınız.

**Comment by sertacates** [comment]
![Ekran görüntüsü 2022-07-31 124624](https://user-images.githubusercontent.com/34302399/182020759-a5798ef5-d3a6-432f-8990-c8662d0cc53f.jpg)
![Ekran görüntüsü 2022-07-31 125014](https://user-images.githubusercontent.com/34302399/182020761-89a3b98d-9de0-4d20-9403-f6d18d2b441b.jpg)


Yaptığımız toplantıdaki kararlarımız bu şekildeydi. Ara Yüz kısmında Seyithan Toprak sen bayağı ilerledin. Eray diğer kısma baksın, sen Ara Yüzden sorumlu ol. Konuyu doğrudan sana bağlıyoruz. (Assigneer oldun @S-Toprak )

**Comment by ErAk042** [comment]
Bu hali iş görür bence. TDDİ kısmında ben de yardımcı olacağım

**Comment by S-Toprak** [comment]
Hocam Eray'la beraber verilen dönütlere göre iyileştirmeleri yapar, kodları güncellerim.

**Comment by sertacates** [comment]
Tamamdır Seyithan Toprak, github'a dosyaları yüklemeyi unutma, güncelleme yapınca haber verirsin. Yine son haline ZOOM ile bakarız.

**Comment by S-Toprak** [comment]
Hocam şu anki halini Github'a koydum, verdiğiniz dönütlere göre güncelleyip yeni halini de bitince koyarım.

**Comment by sertacates** [comment]
Seyithan Toprak, düğmenin rengi müthiş olmuş. Sıralama için aşağı açılır listedeki (drop down menu) maddeleri doldurmuşsun. Ara Yüzü 10 ağustosa kadar öteleyebiliriz.

**Comment by sertacates** [comment]
Seyithan Toprak, Ara Yüzde son durum nedir?

**Comment by S-Toprak** [comment]
Hocam son yapılan Mentor toplantısında aldığımız kararların ardından eğer uygunsa arayüz işine şimdilik ara veriyorum.

**Comment by sertacates** [comment]
Bugünkü e-posta doğrultusunda sadece veri doldurmaya yöneliyoruz.

**Comment by S-Toprak** [comment]
O zaman şimdilik Issue'yı kapatıyorum hocam

**Comment by sertacates** [comment]
Eline sağlık Seyithan Toprak, kapatabilirsin. Uygundur.
