### ISSUE TITLE
"Doğal Dil İşleme- İsmail Arı Yaz Okulu 2018" videolarını izleyelim.

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#7]
[Doğal Dil İşleme- İsmail Arı Yaz Okulu 2018](https://www.youtube.com/watch?v=CzIUICJXAjY&list=PLMGWwuh6-mEe57iOtf1uo5DgZB288l0CQ) Bu bağlantıdan "Doğal Dil İşleme- İsmail Arı Yaz Okulu 2018" başlığında toplanan 6 videoyu izleyelim. Hem Doğal Dil İşleme hakkında genel bir bilgimiz olur hem de "Arama Motoru Geliştirme Döngüsü - Emine Yılmaz" videosu projemiz ile ilgili bize biraz ipucu sağlar.

**Comment by ErAk042** [comment]
Hocam ben arama motoru videosunu izledim diğerleri de 24 temmuz'a kalmadan biter.

**Comment by S-Toprak** [comment]
Hocam benim de durum Eray'la aynı, 24 Temmuzda duruma göre issue'yı Done' a alırız şu an in progressa alıyorum

**Comment by sertacates** [comment]
Tamamdır. Bitiren buraya belirtsin. İkinci bitiren de DONE (Yapılmış/Bitmiş) bölümüne konuyu (issue) taşısın.

**Comment by ErAk042** [comment]
Ben izlemeyi bittirdim hocam

**Comment by S-Toprak** [comment]
Benimkiler de bitti hocam, issue'yı kapatıyorum

**Comment by sertacates** [comment]
Problem çözerken aklınıza bunlarda gelir. Gerektiğinde yeni konu açarak tartışalım.
