### ISSUE TITLE
Literatür taraması tamamlandı mı?

### ISSUE THREAD

**Issue by sertacates** [iflGARAJI10100/taMAM#8]
NLP ile ilgili örnek arama motorlarını github üzerinden bulup inceleyelim demiştik. Bulduklarımızı bir araya getirip bir zoom toplantısı yapalım mı? Bu toplantının ana gündemi arama motoru ile ilgili iş ve işlemleri ortaya çıkarmak olsun mu? Bu toplantıda artık görev bölümü yapıp arama motorumuza başlayalım mı? "learn to rank" ile ilgili farklı bir uygulama gözünüze çarptı mı?

**Comment by S-Toprak** [comment]
Elimizde Eray'la bulduğumuz birkaç kaynak ve sunumlar var hocam, eğer Eray'a da uygunsa pazar günü bir toplantı yaparız ve konuyu Done a alırız. Şu an in progresse koyuyorum.

**Comment by ErAk042** [comment]
Bana uygundur

**Comment by sertacates** [comment]
Gençler, literatür araştırmamızın hepsini değil de projede kullandığımız kaynakları README'ye yavaş yavaş işleyelim mi? @S-Toprak @ErAk042

**Comment by S-Toprak** [comment]
Hocam döküman arayışımıza Eray'la devam ediyoruz

**Comment by ErAk042** [comment]
Çalışmaya hala devam ediyoruz hocam parça parça atarız buldukça

**Comment by sertacates** [comment]
Gençler, hala readme.md dosyasında dokümantasyon kaynakça görmüyoruz. Discussion içinde konuyu hızlandıralım ve çıktıları readme.md'ye ekleyelim.

**Comment by sertacates** [comment]
Alanyazında (literatürde) https://towardsdatascience.com/17-types-of-similarity-and-dissimilarity-measures-used-in-data-science-3eb914d2681 gibi metrikler dışında arama için ne kullanacağımıza baktınız mı hugginface'ten sentence similarity mi yapacağız?

**Comment by S-Toprak** [comment]
Arama kısmı çıkarıldığı için literatür taramasına gerek kalmadı hocam.

**Comment by sertacates** [comment]
Elinize sağlık gençler, artık yarışma gününü bekleyeceğiz.
